---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install -g broccoli-cli
  - yarn

script:
  - npm test
